export const URL_WEB = 'http://localhost:8080/shop-api'
export const URL_USER = 'http://localhost:3000/users'
export const URL_PRODUCT = 'http://localhost:8080/shop-api/product'
export const URL_CART = 'http://localhost:8080/shop-api/cart/me'
export const URL_CATEGORY = 'http://localhost:8080/shop-api/category/all'
